<?php

declare(strict_types=1);

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;

class GenerateProjectState extends Command
{
    protected $signature = 'jaosoft:project-state';

    protected $description = 'Generate PROJECT_STATE.md from engram.json';

    public function handle(): int
    {
        $path = base_path('engram.json');

        if (! File::exists($path)) {
            $this->error('engram.json not found at project root.');

            return Command::FAILURE;
        }

        $data = json_decode(File::get($path), true, flags: JSON_THROW_ON_ERROR);

        $markdown = $this->buildMarkdown($data);

        File::put(base_path('PROJECT_STATE.md'), $markdown);

        $this->info('PROJECT_STATE.md generated successfully.');

        return Command::SUCCESS;
    }

    private function buildMarkdown(array $data): string
    {
        $md = "# {$data['project']}\n\n";
        $md .= "> **Version:** {$data['version']} | **Status:** {$data['status']} | **Updated:** {$data['last_updated']}\n\n";

        $md .= "## Stack\n\n";
        $md .= '| Technology | Version |'."\n";
        $md .= '|---|---|'."\n";
        foreach ($data['stack'] as $tech => $version) {
            $md .= "| {$tech} | {$version} |\n";
        }
        $md .= "\n";

        $md .= "## Modules\n\n";
        foreach ($data['modules'] as $key => $module) {
            $md .= "### {$key}\n\n";
            $md .= "- **Status:** {$module['status']}\n";
            $md .= "- **Last check:** {$module['last_check']}\n";

            if (! empty($module['features'])) {
                $md .= "- **Features:**\n";
                foreach ($module['features'] as $feature) {
                    $md .= "  - {$feature}\n";
                }
            }

            if (! empty($module['notes'])) {
                $md .= "- **Notes:** {$module['notes']}\n";
            }

            if (! empty($module['resources_tenant'])) {
                $md .= "- **Tenant Resources:**\n";
                foreach ($module['resources_tenant'] as $r) {
                    $md .= "  - {$r}\n";
                }
            }

            if (! empty($module['resources_superadmin'])) {
                $md .= "- **Superadmin Resources:**\n";
                foreach ($module['resources_superadmin'] as $r) {
                    $md .= "  - {$r}\n";
                }
            }

            if (! empty($module['bug_fixes'])) {
                $md .= "- **Bug fixes:**\n";
                foreach ($module['bug_fixes'] as $fix) {
                    $md .= "  - {$fix}\n";
                }
            }

            if (! empty($module['roles_defined'])) {
                $md .= '- **Roles:** '.implode(', ', $module['roles_defined'])."\n";
            }

            if (! empty($module['checklist'])) {
                $md .= "- **Checklist:** `{$module['checklist']}`\n";
            }

            $md .= "\n";
        }

        $md .= "## Test Suite\n\n";
        $md .= "- **Total tests:** {$data['test_suite']['total_tests']}\n";
        $md .= "- **Passing:** {$data['test_suite']['passing']}\n";
        $md .= "- **Assertions:** {$data['test_suite']['assertions']}\n";
        $md .= "- **Status:** {$data['test_suite']['status']}\n";
        $md .= "- **Last run:** {$data['test_suite']['last_run']}\n";
        $md .= "\n";

        $md .= "## Architecture Rules\n\n";
        foreach ($data['architecture_rules'] as $rule => $enabled) {
            $md .= "- **{$rule}:** ".($enabled ? '✅' : '❌')."\n";
        }
        $md .= "\n";

        $md .= "## Features Implemented\n\n";
        foreach ($data['features_existing'] as $feature) {
            $md .= "- {$feature}\n";
        }
        $md .= "\n";

        $md .= "## Security Status\n\n";
        foreach ($data['security_status'] as $item => $status) {
            $md .= "- **{$item}:** {$status}\n";
        }
        $md .= "\n";

        if (! empty($data['next_actions'])) {
            $md .= "## Next Actions\n\n";
            foreach ($data['next_actions'] as $action) {
                $md .= "- [ ] {$action}\n";
            }
            $md .= "\n";
        }

        $md .= "---\n\n";
        $md .= "> **Source:** `engram.json` | **Generated by:** `php artisan jaosoft:project-state`\n";

        return $md;
    }
}
