services:
  - type: web
    name: saas-core
    runtime: docker
    dockerfilePath: ./Dockerfile
    region: frankfurt
    plan: free
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: LOG_CHANNEL
        value: stack
      - key: SESSION_DRIVER
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: CACHE_STORE
        value: database
      - key: FILESYSTEM_DISK
        value: s3
      - key: REDIS_CLIENT
        value: phpredis
      - key: APP_KEY
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_DEFAULT_REGION
        value: auto
      - key: AWS_BUCKET
        sync: false
      - key: AWS_USE_PATH_STYLE_ENDPOINT
        value: "true"
      - key: AWS_ENDPOINT
        value: https://fly.storage.tigris.dev

  - type: redis
    name: saas-core-redis
    region: frankfurt
    plan: free

databases:
  - name: saas-core-db
    databaseName: saas_core
    user: saas_core
    region: frankfurt
    plan: free
    postgresMajorVersion: "16"   
